version: '3.3'

services:
   db:
     image: mysql:latest
     volumes:
       - /spare/dockerdata/mysqldb:/var/lib/mysql
     restart: always
     ports:
     - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       
       
       
      
  
